"""change signature

Revision ID: 392bed2a4279
Revises: ecf77e740004
Create Date: 2024-10-10 15:27:20.743490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '392bed2a4279'
down_revision: Union[str, None] = 'ecf77e740004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_post_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_post_id_fkey', 'files', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
